window.PLACES = [
  {
    id: "dining-sdaf",
    name: "Sdaf Restaurant",
    category: "Dining",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Sdaf Restaurant, Abha, Saudi Arabia",
    image: "./images/place1.jpg",
    alt: "A southern Saudi meal at Sdaf Restaurant in Abha",
    description: "Authentic southern dishes including Areeqah and traditional local specialties",
    planTime: "12:30",
    priority: 1
  },
  {
    id: "dining-haneeth-mollah",
    name: "Traditional Haneeth (Mollah)",
    category: "Dining",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Traditional Haneeth Mollah, Abha, Saudi Arabia",
    image: "./images/place2.jpg",
    alt: "Traditional slow-cooked Haneeth served in Abha",
    description: "Authentic Aseer Haneeth cooked over local herbs and traditional slow-cooked lamb",
    planTime: "13:00",
    priority: 2
  },
  {
    id: "dining-ala-bali",
    name: "Ala Bali Restaurant",
    category: "Dining",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Ala Bali Restaurant, Abha, Saudi Arabia",
    image: "./images/place3.jpg",
    alt: "A cozy dining setting at Ala Bali Restaurant in Abha",
    description: "A delightful dining spot offering delicious meals with a cozy atmosphere",
    planTime: "19:00",
    priority: 3
  },
  {
    id: "cafe-haiz",
    name: "Haiz Cafe",
    category: "Cafes",
    seasons: ["All Year"],
    duration: "45–60 minutes",
    mapQuery: "Haiz Cafe, Abha, Saudi Arabia",
    image: "./images/place4.jpg",
    alt: "A specialty coffee setting at Haiz Cafe in Abha",
    description: "Specialty coffee with a unique atmosphere in the heart of Abha",
    planTime: "09:00",
    priority: 1
  },
  {
    id: "cafe-neighbor-house",
    name: "The Neighbor House",
    category: "Cafes",
    seasons: ["All Year"],
    duration: "45–60 minutes",
    mapQuery: "The Neighbor House, Abha, Saudi Arabia",
    image: "./images/place5.jpg",
    alt: "Coffee and baked goods at The Neighbor House in Abha",
    description: "A warm and inviting coffee house offering modern beverages and baked goods",
    planTime: "10:00",
    priority: 2
  },
  {
    id: "cafe-redhah",
    name: "Redhah Cafe",
    category: "Cafes",
    seasons: ["All Year"],
    duration: "45–60 minutes",
    mapQuery: "Redhah Cafe, Abha, Saudi Arabia",
    image: "./images/place6.jpg",
    alt: "A calm coffee setting at Redhah Cafe in Abha",
    description: "Serene ambiance and authentic local coffee experiences",
    planTime: "16:00",
    priority: 3
  },
  {
    id: "cafe-black-by-location",
    name: "Black by Location",
    category: "Cafes",
    seasons: ["All Year"],
    duration: "45–60 minutes",
    mapQuery: "Black by Location, Abha, Saudi Arabia",
    image: "./images/place7.jpg",
    alt: "Specialty coffee at Black by Location in Abha",
    description: "Sleek and modern specialty coffee destination with exceptional brews",
    planTime: "17:00",
    priority: 4
  },
  {
    id: "heritage-al-nasb",
    name: "Al Nasb Heritage Village",
    category: "Heritage & Markets",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Al Nasb Heritage Village, Abha, Saudi Arabia",
    image: "./images/place8.jpg",
    alt: "Historic Aseeri architecture at Al Nasb Heritage Village",
    description: "Historic Aseeri architecture and rich local heritage in an authentic village setting",
    planTime: "10:30",
    priority: 1
  },
  {
    id: "heritage-tuesday-market",
    name: "Tuesday Market (Souk Al-Thulatha)",
    category: "Heritage & Markets",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Tuesday Market Souk Al-Thulatha, Abha, Saudi Arabia",
    image: "./images/place9.jpg",
    alt: "Traditional goods at Tuesday Market in Abha",
    description: "Browse local textiles, fragrant spices, and traditional handicrafts at Abha's historic market",
    planTime: "11:00",
    priority: 2
  },
  {
    id: "heritage-rijal-almaa",
    name: "Rijal Almaa Heritage Village",
    category: "Heritage & Markets",
    seasons: ["Winter & Spring"],
    duration: "2–3 hours",
    mapQuery: "Rijal Almaa Heritage Village, Saudi Arabia",
    image: "./images/place10.jpg",
    alt: "Stone palaces in Rijal Almaa Heritage Village",
    description: "Iconic gingerbread stone palaces and historic museums in a warm valley setting",
    planTime: "09:30",
    priority: 1
  },
  {
    id: "heritage-tabab",
    name: "Tabab Village",
    category: "Heritage & Markets",
    seasons: ["All Year"],
    duration: "1–2 hours",
    mapQuery: "Tabab Village, Abha, Saudi Arabia",
    image: "./images/place11.jpg",
    alt: "Historic buildings near Tabab Village in Aseer",
    description: "A historic village filled with ancient mosques and deep historical roots",
    planTime: "14:00",
    priority: 3
  },
  {
    id: "activity-seven-abha",
    name: "Seven Abha",
    category: "Activities & Nature",
    seasons: ["All Year"],
    duration: "2–3 hours",
    mapQuery: "Seven Abha, Saudi Arabia",
    image: "./images/place12.jpg",
    alt: "Leisure spaces at Seven Abha",
    description: "The newest modern entertainment hub featuring vibrant dining and leisure options",
    planTime: "15:00",
    priority: 1
  },
  {
    id: "activity-hiking-trails",
    name: "Mountain Hiking Trails",
    category: "Activities & Nature",
    seasons: ["Summer & Rainy Season"],
    duration: "3–4 hours",
    mapQuery: "Mountain hiking trails, Abha, Saudi Arabia",
    image: "./images/place13.jpg",
    alt: "A mountain hiking path in the Aseer highlands",
    description: "Guided mountain hiking adventures through dramatic nature and cliffside paths",
    planTime: "08:00",
    priority: 1
  },
  {
    id: "activity-meditation-soudah",
    name: "Meditation at Soudah Peaks",
    category: "Activities & Nature",
    seasons: ["Summer & Rainy Season"],
    duration: "1–2 hours",
    mapQuery: "Soudah Peaks, Abha, Saudi Arabia",
    image: "./images/place14.jpg",
    alt: "Misty mountain scenery at Soudah Peaks",
    description: "Relaxation and mindfulness sessions high above the clouds and mist",
    planTime: "09:00",
    priority: 2
  },
  {
    id: "activity-bani-mazen",
    name: "Bani Mazen Villages",
    category: "Activities & Nature",
    seasons: ["Summer & Rainy Season"],
    duration: "2–3 hours",
    mapQuery: "Bani Mazen Villages, Aseer, Saudi Arabia",
    image: "./images/place15.jpg",
    alt: "Green mountain valleys near Bani Mazen Villages",
    description: "Scenic mountain valleys, lush greenery, and serene countryside atmosphere",
    planTime: "11:30",
    priority: 3
  },
  {
    id: "activity-strawberry-farm",
    name: "Strawberry Farm (Soudah)",
    category: "Activities & Nature",
    seasons: ["Summer & Rainy Season"],
    duration: "1–2 hours",
    mapQuery: "Strawberry Farm Soudah, Abha, Saudi Arabia",
    image: "./images/place16.jpg",
    alt: "Strawberries growing in the Soudah mountain area",
    description: "Interactive strawberry picking experience in the chilly mountain atmosphere",
    planTime: "13:30",
    priority: 4
  },
  {
    id: "activity-honey-hut",
    name: "Honey Hut",
    category: "Activities & Nature",
    seasons: ["All Year"],
    duration: "45–60 minutes",
    mapQuery: "Honey Hut, Abha, Saudi Arabia",
    image: "./images/place17.jpg",
    alt: "Local mountain honey at a Honey Hut in Aseer",
    description: "Taste pure organic mountain honey and learn about local beekeeping traditions",
    planTime: "12:00",
    priority: 5
  },
  {
    id: "activity-art-street",
    name: "Art Street",
    category: "Activities & Nature",
    seasons: ["Jacaranda & Spring"],
    duration: "1–2 hours",
    mapQuery: "Art Street, Abha, Saudi Arabia",
    image: "./images/place18.jpg",
    alt: "Purple Jacaranda trees along Art Street in Abha",
    description: "A vibrant pedestrian path surrounded by blooming purple Jacaranda trees",
    planTime: "17:30",
    priority: 1
  }
];
