window.PLACES = [
  {
    id: 1,
    name: "Jabal Soudah",
    category: "Nature",
    season: "Summer",
    duration: "2–3 hours",
    mapQuery: "Jabal Soudah, Abha, Saudi Arabia",
    image: "./images/place1.jpg",
    alt: "Misty mountain ridges at Jabal Soudah",
    description: "Reach Aseer's highest viewpoints for cool air, cloud trails, and sweeping highland scenery.",
    planTime: "09:00",
    priority: 1
  },
  {
    id: 2,
    name: "Rijal Almaa Heritage Village",
    category: "Heritage",
    season: "All year",
    duration: "2 hours",
    mapQuery: "Rijal Almaa Heritage Village, Saudi Arabia",
    image: "./images/place2.jpg",
    alt: "Historic stone towers in Rijal Almaa Heritage Village",
    description: "Walk between colourful stone towers and discover the stories of one of Saudi Arabia's most admired villages.",
    planTime: "10:00",
    priority: 1
  },
  {
    id: 3,
    name: "Al Soudah Park",
    category: "Nature",
    season: "Summer",
    duration: "1–2 hours",
    mapQuery: "Al Soudah Park, Abha, Saudi Arabia",
    image: "./images/place3.jpg",
    alt: "Green juniper woodland in Al Soudah Park",
    description: "Pause among fragrant juniper trees, picnic overlooks, and misty paths in the highlands.",
    planTime: "12:00",
    priority: 2
  },
  {
    id: 4,
    name: "Abha High City",
    category: "Views",
    season: "All year",
    duration: "1 hour",
    mapQuery: "Abha High City, Saudi Arabia",
    image: "./images/place4.jpg",
    alt: "City and mountain view from Abha High City",
    description: "Take in Abha from above, especially at golden hour when city lights meet the surrounding peaks.",
    planTime: "17:30",
    priority: 2
  },
  {
    id: 5,
    name: "Al Muftaha Village",
    category: "Arts",
    season: "All year",
    duration: "1–2 hours",
    mapQuery: "Al Muftaha Village, Abha, Saudi Arabia",
    image: "./images/place5.jpg",
    alt: "Colourful art details at Al Muftaha Village",
    description: "See galleries, craft studios, and the vivid visual language that reflects Aseer's creative spirit.",
    planTime: "14:00",
    priority: 1
  },
  {
    id: 6,
    name: "Shada Palace",
    category: "Heritage",
    season: "All year",
    duration: "1 hour",
    mapQuery: "Shada Palace, Abha, Saudi Arabia",
    image: "./images/place6.jpg",
    alt: "Traditional architecture at Shada Palace",
    description: "Visit a landmark of old Abha architecture, with a compact museum setting and central-city location.",
    planTime: "11:30",
    priority: 2
  },
  {
    id: 7,
    name: "Abha Dam Lake",
    category: "Nature",
    season: "Spring",
    duration: "1–2 hours",
    mapQuery: "Abha Dam Lake, Saudi Arabia",
    image: "./images/place7.jpg",
    alt: "Water and hills at Abha Dam Lake",
    description: "Enjoy a quieter waterside walk where the lake reflects Abha's green hills and changing skies.",
    planTime: "16:00",
    priority: 2
  },
  {
    id: 8,
    name: "Al Habala Hanging Village",
    category: "Heritage",
    season: "Winter",
    duration: "2–3 hours",
    mapQuery: "Al Habala Village, Saudi Arabia",
    image: "./images/place8.jpg",
    alt: "Mountain landscape around Al Habala Hanging Village",
    description: "Explore the dramatic mountain setting of a village shaped by Aseer's cliffside geography.",
    planTime: "09:30",
    priority: 1
  },
  {
    id: 9,
    name: "Al Qaraa Hill",
    category: "Views",
    season: "Winter",
    duration: "1 hour",
    mapQuery: "Al Qaraa Hill, Abha, Saudi Arabia",
    image: "./images/place9.jpg",
    alt: "Mountain viewpoint from Al Qaraa Hill",
    description: "Choose this open hillside for clear views across the highlands and a calm sunset stop.",
    planTime: "17:00",
    priority: 2
  },
  {
    id: 10,
    name: "Aseer National Park",
    category: "Nature",
    season: "Spring",
    duration: "3–4 hours",
    mapQuery: "Aseer National Park, Saudi Arabia",
    image: "./images/place10.jpg",
    alt: "Forest landscape in Aseer National Park",
    description: "Follow forest roads and trails through one of the Kingdom's most important highland landscapes.",
    planTime: "08:30",
    priority: 1
  },
  {
    id: 11,
    name: "Al Nasb Heritage Museum",
    category: "Heritage",
    season: "All year",
    duration: "1 hour",
    mapQuery: "Al Nasb Heritage Museum, Abha, Saudi Arabia",
    image: "./images/place11.jpg",
    alt: "Heritage objects displayed in an Abha museum",
    description: "Add a thoughtful cultural pause with local objects, stories, and traditional Aseeri details.",
    planTime: "13:30",
    priority: 3
  },
  {
    id: 12,
    name: "Tuesday Market",
    category: "Markets",
    season: "All year",
    duration: "1–2 hours",
    mapQuery: "Tuesday Market, Abha, Saudi Arabia",
    image: "./images/place12.jpg",
    alt: "Market displays at Tuesday Market in Abha",
    description: "Browse local textiles, fragrant spices, and everyday finds at one of Abha's liveliest cultural stops.",
    planTime: "10:30",
    priority: 1
  },
  {
    id: 13,
    name: "Green Mountain",
    category: "Views",
    season: "Summer",
    duration: "1 hour",
    mapQuery: "Green Mountain, Abha, Saudi Arabia",
    image: "./images/place13.jpg",
    alt: "Illuminated Green Mountain above Abha",
    description: "Finish an evening with the illuminated hillside landmark and a view across the city below.",
    planTime: "19:00",
    priority: 1
  },
  {
    id: 14,
    name: "Al Sahab Park",
    category: "Nature",
    season: "Summer",
    duration: "1–2 hours",
    mapQuery: "Al Sahab Park, Abha, Saudi Arabia",
    image: "./images/place14.jpg",
    alt: "Clouds drifting over a mountain viewpoint at Al Sahab Park",
    description: "Come for the cloud-level lookout, cool breeze, and a memorable pause above the valleys.",
    planTime: "15:30",
    priority: 1
  }
];
